### ISSUE TITLE
閒聊

### ISSUE THREAD

**Issue by BeautyyuYanli** [RimoChan/Librian#1]
有点想挖坑了.

说不定以后会有个微笙计协x漫研的东西出来?

我说能不能写个好用点的文档啊.这文档看得人脑阔疼.麻烦写一下基本的调试和输出指令好嘛.

**Comment by RimoChan** [comment]
嗯？文檔是說 rimochan.github.io 的吗？那個是使用方法，不是給開發者看的文檔……

**Comment by BeautyyuYanli** [comment]
即使是使用方法也好难用啊.它怎么输出啊 输出产品是html/js吗还是啥的?

**Comment by RimoChan** [comment]
不不不，是解釋不是編譯，即時繪製html的。

**Comment by BeautyyuYanli** [comment]
还是没懂诶.即时生成html之后用pyqt画出来的吗?

以及我直接执行`python Librrian.py`的话会报错诶

```
python Librian.py 
Traceback (most recent call last):
  File "Librian.py", line 9, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: libQt5WebEngineWidgets.so.5: cannot open shared object file: No such file or directory
```
明明有安装了pyqt5的

**Comment by RimoChan** [comment]
這個好像是你沒裝庫……
但其實你裝了也不行因爲現在的版本在linux上無法運行……參考https://rimochan.github.io/Librian_doc/site/接下來要做的/一些遺憾/

**Comment by BeautyyuYanli** [comment]
有装pyqt5的啊.话说潘大爷是哪位大佬啊.

**Comment by RimoChan** [comment]
潘大爺的話……我也說不清楚，不過如果你認識陳瑞龍，他不是有一件奇怪的衣服嗎，衣服上畫的就是潘大爺……

**Comment by BeautyyuYanli** [comment]
话说啥时候可以弄到android上面啊.现代人好像都不喜欢用电脑来着.

**Comment by RimoChan** [comment]
感覺好複雜……遙遙無期呀，至少先把linux的問題解決了再出吧。
話說拿着手機在外面打黃油有一種露出play的感覺呀……

**Comment by BeautyyuYanli** [comment]
岂不刺激吗.只要声音没有外放的话hhh

**Comment by ShroXd** [comment]
移动端用weex，flutter这种东西做会不会好一点……虽然这些坑也是多的鸭啤
