### ISSUE TITLE
似乎与 inky 有相似之处？

### ISSUE THREAD

**Issue by nobodxbodon** [RimoChan/Librian#12]
觉得 ink 和剧本语言类似：https://www.yuque.com/inky/pcke0w/gix3ga

也许扩展到文字游戏可以有更广用户？毕竟不需图片素材，上手门槛会低不少。

**Comment by RimoChan** [comment]
<sub>其實你以前給我看過ink啦。</sub>

不擴展到文字遊戲有兩點原因——

一是因爲文字遊戲需要一個能在網頁上遊玩的賣點，然而Librian後端沒有JavaScript實現，所以邏輯沒法在網頁上運行。

二是設計的思路，ink有很多增加遊戲性的語法糖，而Librian的語法集中在畫面效果上，所以做文字遊戲沒有什麼優點。

**Comment by nobodxbodon** [comment]
Lol 我的好记性。。。多谢回复
