### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by PlutoNameless** [RimoChan/Librian#2]
如果不能解决用户面向指令编程，那么Librian依旧只是一个重复的轮子。
 比它效率更优秀、素材更多、跨平台更多的引擎不仅只有一个。

**Comment by RimoChan** [comment]
說的好。


我自認爲Librian的思想還是不太面向指令而是面向對象的。如果你看看教程文檔就會發現，在Librian中，人物作爲主要的對象，控制是萬劍歸宗的。(這是什麼比喻……)


比如在Librian中的一句: 
`潘大爺 (笑) 「你好！」`

可以面向對象地作爲: 
`潘大爺.come_to_stage();`
`潘大爺.face('笑');`
`潘大爺.say('你好')`

分解爲繪圖等指令的話就是: 
`people_image.fade_in(潘大爺的身體, 潘大爺的笑臉)`
`name_box.set('潘大爺')`
`word_box.set('你好')`
根據不同的設置也可能同時觸發鏡頭對象:
`other_people.fade_out()`
等等。


相比之下，像 `> BG 教室.png` 這樣真正的指令，實際上出現的次數比對話少得多。出於類似哈夫曼原理的考慮就不太需要簡化。


不過如果你說的「面向指令編程」是和「使用圖形界面製作遊戲」相對的話，我卻是反對的。
一方面是我覺得做圖形界面太麻煩……
另一方面的話，大概並不能提高效率。你想，假如使用圖形界面來做出`潘大爺 (笑) 「你好！」`的話有哪些步驟呢: 
1. 從人物框中用鼠標按住`潘大爺`拖到背景上。
2. 在彈出的下拉框中選擇`潘大爺`的表情`笑`。
3. 點擊文本框，在鍵盤上鍵入`你好！`。

嘛……總共12個字的句子，直接打字應該還快一點。
手在鼠標和鍵盤上切換，不僅需要時間，而且干擾思路，我覺得不好。

**Comment by leftering** [comment]
> 如果不能解决用户面向指令编程，那么Librian依旧只是一个重复的轮子。
> 比它效率更优秀、素材更多、跨平台更多的引擎不仅只有一个。

求推荐一个简明的支持h5的visual novel轮子，最近找轮子找的有点头大

**Comment by RimoChan** [comment]
> 求推荐一个简明的支持h5的visual novel轮子，最近找轮子找的有点头大

……Librian不算嗎？

**Comment by leftering** [comment]
> > 求推荐一个简明的支持h5的visual novel轮子，最近找轮子找的有点头大
> 
> ……Librian不算嗎？

当然是啦 Librian是目前找到的支持h5最好的轮子了
