### ISSUE TITLE
支持支持，以及需要注意的点

### ISSUE THREAD

**Issue by dyxang** [RimoChan/Librian#3]
但是看教程像看单口相声😂
建议还是做个简明版的，毕竟风格不是所有人都能接收。

**Comment by RimoChan** [comment]
我說話不苟言笑的話就說不下去……
因爲我自己也喜歡寫劇本所以漸漸地話就變多了……

我經常都擔心，話少了大家可能會在某些理解上出現偏差，所以填充了很多話……好像沒有起到作用。

啊，對了，下次再叫一個人來一起寫——然後就可以玩對口相聲啦！

**Comment by dyxang** [comment]
@RimoChan
教程蛮详细的，但是如果不多推广就没人知道。
所以还是要多推广💪，既然都在知乎上写了文章，为什么不回答些问题来推广呢。
比如知乎上有“galgame引擎推荐”的那种问题。
还有就是github下大文件有点慢，建议增加备用下载地址。

**Comment by RimoChan** [comment]
嗯，看了你的建議以後，我剛纔去知乎回答問題了。
我猜你用的是很貴的電信網——移動的國際出口就比較好。
其實教程的安裝章節提到了「可以去mega下載」，大概是廢話太多把有用的東西遮住了……

**Comment by dyxang** [comment]
> 嗯，看了你的建議以後，我剛纔去知乎回答問題了。
> 我猜你用的是很貴的電信網——移動的國際出口就比較好。
> 其實教程的安裝章節提到了「可以去mega下載」，大概是廢話太多把有用的東西遮住了……

@RimoChan 嗯……没有问题是手机上下太慢了，用电脑一下就下下来了。
但是点击 面板.exe 时显示
```qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

从release下载，没有安装python，win10，文件夹在E盘，文件夹含有中文名

**Comment by RimoChan** [comment]
@dyxang release版自帶python，不過Librian文件夾居然不能有中文……
你不說我還沒發現這個問題，我試着在文件夾名裏加了中文，果然也不行了。
我本來沒有exe文件，那個exe是用pyinstaller直接把幾個命令捆在一起生成的，pyinstaller這東西比較有鬼……我準備拿c++寫一個面板入口。

**Comment by dyxang** [comment]
@RimoChan 还有，视频竟然是用手机录的……？

**Comment by RimoChan** [comment]
@dyxang 欸……不是啊，我用的是屏幕錄影。是不是我很少做視頻，沒搞清楚編碼，然後弄得畫面不清楚？

**Comment by dyxang** [comment]
@dyxang 好吧屏幕一暗我就以为是手机录的……
配置文檔里面能用简体吗？

**Comment by RimoChan** [comment]
@dyxang 項目名不行，值可以用簡體。
這樣說起來，混用的話確實會有不習慣的人……下個版本說不定就可以用簡體啦。
還有你@的是自己(笑)

**Comment by dyxang** [comment]
@RimoChan ……
也就是说，我可以这样？
```    潘大爺:
        衣:
            _默认:
                - 衣/制服
            常服:
                - 衣/常服
        顏: 
            _默认:
                - 顏/通常
            笑:
                - 顏/笑
            怒:
                - 顏/怒
                - 特效/怒氣特效

```

**Comment by RimoChan** [comment]
@dyxang 
「下劃線開頭的」以及最左邊那排的「衣」「顏」這些是寫在代碼裏的所以只能按我原本的，其他就隨意啦。

**Comment by dyxang** [comment]
（已修改）
文檔在 Librian_doc 里，我竟然沒有去找……
