### ISSUE TITLE
有没有可能开一个网站, 供用户在线编辑剧本并生成在线游戏?

### ISSUE THREAD

**Issue by nobodxbodon** [RimoChan/Librian#4]
用户在这个站可创作游戏并选择发布, 并可以试玩所有其他人发布(并通过审核)的游戏.
感觉这样由用户创造游戏内容的模式会比较容易积累人气, 有助推广.
如果有意的话, 可问下组里或者其他开源社区有没有同道.

**Comment by RimoChan** [comment]
隔壁[輕文](https://www.iqing.com)就是這樣的網站(笑)。
(不好，輕文沒給我錢，不能幫他做廣告！)

一方面是，Librian主要面向的還是windows平臺，更希望創作者刻盤賣錢或者上steam賣錢……html獨立版本只能試用劇本功能沒法執行邏輯。
另一方面，開網站的話會有政府審查的問題，畢竟不能搞成非法網站(收入全靠澳門賭博的廣告)。

(不過我突然想起來用js的python解釋器其實是可以的！)

**Comment by nobodxbodon** [comment]
哦. 刚看了一下, 相比轻文的[IQA引擎](https://zh.moegirl.org/IQA_Engine), Librian在生成游戏的功能上有什么不同呢? 可以由用户选择决定故事走向吗?

内容审核确实是个问题. 昨天那个[基于git的bbs工具](https://www.v2ex.com/t/532941#reply4)的想法也有省去建站麻烦的考虑(把github的repo作为后端数据库).

**Comment by RimoChan** [comment]
嗯，都可以由用戶(玩遊戲的人)決定故事走向。在生成的遊戲上大體什麼大的不同——類似於asm和c++寫的exe用起來沒有什麼不同，但是c++寫的時候比較舒服。

如果大家把工程放在github上，所有的內容不經過網站，由遊玩者訪問repo中的資源文件來實現服務的話。創作者的工程本身需要版本控制，應該是不違反github條例的。不過網站管理者是不是不用對創作者的內容負審查義務……雖然想這樣說，不過真出事被抓走的話可沒地方說理，所以還是算了。

**Comment by nobodxbodon** [comment]
了解. 用repo管理内容并不意味着所有人可以任意(匿名)提交内容. 设想中, 假如是以PR的形式来提交的话, repo管理员可以审核/建议/拒绝.
无论如何, 内容审核都是个苦差. 没有团队运作是挺难的.
