### ISSUE TITLE
是不是有更合適的擴展名？

### ISSUE THREAD

**Issue by RimoChan** [RimoChan/Librian#5]
劇本文件的擴展名是「.play」似乎不太合適，因爲play看起來像「玩」，而且能讓人聯想到色情的play(笑)。就算作爲劇本，Librian的劇本不能代表所有劇本。

對此有什麼好的建議嗎？

**Comment by nobodxbodon** [comment]
`.剧本`

**Comment by RimoChan** [comment]
@nobodxbodon 問題是「劇本」還包括了別的引擎的劇本(未來肯定還有別的中文劇本)，就好像c的代碼文件叫`.c`不能叫`.code`……

**Comment by nobodxbodon** [comment]
几个思路: 
- 与性质/功能相关, 如`.cmd`, `.txt`等. 那么就从准确描述这个文件的作用开始?
- 与工具本身名称相关, 如C plus plus -> `.cpp`, 那么就从`librian`或者对应的中文开始考虑?

**Comment by RimoChan** [comment]
@nobodxbodon 考慮劇本文件的作用的話就會變成`.劇本`……
從librian考慮的話，叫`.librian`或者`.librian劇本`又太長了(順便吐槽coffeescript)，簡寫成`.lib`就變成了其他的東西(笑)……不過突然想起來，本來librian就是我造的詞，不如就用詞根`.liber`，正好也是書的意思。

**Comment by RimoChan** [comment]
`.liber` 用了一段時間，應該是確定了。
