### ISSUE TITLE
可否将一些功能模块独立成库发布到pypi?

### ISSUE THREAD

**Issue by nobodxbodon** [RimoChan/Librian#6]
之前发布过一个[很简单的API](https://github.com/program-in-chinese/zhconverter), 对中文命名的推广蛮有用(使用者会[立刻注意到](https://www.v2ex.com/t/480623)API是中文命名).

**Comment by RimoChan** [comment]
代碼寫的太差(笑)
因爲高耦合所以並沒有能獨立出來的庫……

**Comment by nobodxbodon** [comment]
[导出轻文](https://github.com/RimoChan/Librian/blob/master/%E5%B0%8E%E5%87%BA%E8%BC%95%E6%96%87.py)似乎可以提取出一些util?

**Comment by RimoChan** [comment]
那個是亂做的……當時想放點在線demo，因此編譯出輕文的劇本，不過現在Librian可以導出html就沒有必要用了。
而且[輕文](www.iqing.com)被查封了，現在他們主頁寫着「主管部門來抓人了，我們不敢開了」(笑)。

**Comment by RimoChan** [comment]
(我纔想起還有這個issue)終於上pypi了！

**Comment by nobodxbodon** [comment]
是指 [liber-language](https://github.com/librian-center/liber-language) 吗？恭喜！

**Comment by RimoChan** [comment]
liber是之前上的，現在librian本體也上了pip呀。

**Comment by nobodxbodon** [comment]
吼吼果然，看走眼了

**Comment by nobodxbodon** [comment]
看到 release 里只有 windows 版本。确认一下，是否 pip 安装也只能在 windows 下运行呢？

**Comment by RimoChan** [comment]
我记得应该是可以跨平台的，其他平台上的测试结果我记不清楚了……

**Comment by nobodxbodon** [comment]
刚在 mac 和 win7 下试了，都报错：
```
$ pip install librian
ERROR: Could not find a version that satisfies the requirement librian (from versions: none)
ERROR: No matching distribution found for librian
```
是有什么依赖项吗？

**Comment by RimoChan** [comment]
可能是你的python太新了，librian太久没更新，现在只能支持python3.6和3.7了……

**Comment by nobodxbodon** [comment]
用的是 3.7.6 和 3.7.9，不过win7 下安装 release 版是可以。
